I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2587, in script
    show aang senyum 1
Exception: Image 'aang senyum' does not accept attributes '1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2587, in script
    show aang senyum 1
  File "D:\Ren'Py\renpy-8.2.1-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\Ren'Py\renpy-8.2.1-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "D:\Ren'Py\renpy-8.2.1-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\Ren'Py\renpy-8.2.1-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "D:\Ren'Py\renpy-8.2.1-sdk\renpy\display\transform.py", line 1089, in _duplicate
    args.extraneous()
  File "D:\Ren'Py\renpy-8.2.1-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'aang senyum' does not accept attributes '1'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Nusantara Quest 1.0
Fri Jun  7 20:16:53 2024
